//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YandexSpeller
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://speller.yandex.net/services/spellservice", ConfigurationName="YandexSpeller.SpellServiceSoap")]
    public interface SpellServiceSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://speller.yandex.net/services/spellservice/checkText", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<YandexSpeller.checkTextResponse> checkTextAsync(YandexSpeller.checkTextRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://speller.yandex.net/services/spellservice/checkTexts", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<YandexSpeller.checkTextsResponse> checkTextsAsync(YandexSpeller.checkTextsRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://speller.yandex.net/services/spellservice")]
    public partial class SpellError
    {
        
        private string wordField;
        
        private string[] sField;
        
        private int codeField;
        
        private int posField;
        
        private int rowField;
        
        private int colField;
        
        private int lenField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string word
        {
            get
            {
                return this.wordField;
            }
            set
            {
                this.wordField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("s", Order=1)]
        public string[] s
        {
            get
            {
                return this.sField;
            }
            set
            {
                this.sField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int pos
        {
            get
            {
                return this.posField;
            }
            set
            {
                this.posField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int row
        {
            get
            {
                return this.rowField;
            }
            set
            {
                this.rowField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int col
        {
            get
            {
                return this.colField;
            }
            set
            {
                this.colField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int len
        {
            get
            {
                return this.lenField;
            }
            set
            {
                this.lenField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CheckTextRequest", WrapperNamespace="http://speller.yandex.net/services/spellservice", IsWrapped=true)]
    public partial class checkTextRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://speller.yandex.net/services/spellservice", Order=0)]
        public string text;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://speller.yandex.net/services/spellservice", Order=1)]
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string lang;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://speller.yandex.net/services/spellservice", Order=2)]
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(0)]
        public int options;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://speller.yandex.net/services/spellservice", Order=3)]
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute("")]
        public string format;
        
        public checkTextRequest()
        {
        }
        
        public checkTextRequest(string text, string lang, int options, string format)
        {
            this.text = text;
            this.lang = lang;
            this.options = options;
            this.format = format;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CheckTextResponse", WrapperNamespace="http://speller.yandex.net/services/spellservice", IsWrapped=true)]
    public partial class checkTextResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://speller.yandex.net/services/spellservice", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("error", IsNullable=false)]
        public YandexSpeller.SpellError[] SpellResult;
        
        public checkTextResponse()
        {
        }
        
        public checkTextResponse(YandexSpeller.SpellError[] SpellResult)
        {
            this.SpellResult = SpellResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CheckTextsRequest", WrapperNamespace="http://speller.yandex.net/services/spellservice", IsWrapped=true)]
    public partial class checkTextsRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://speller.yandex.net/services/spellservice", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("text")]
        public string[] text;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://speller.yandex.net/services/spellservice", Order=1)]
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string lang;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://speller.yandex.net/services/spellservice", Order=2)]
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(0)]
        public int options;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://speller.yandex.net/services/spellservice", Order=3)]
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute("")]
        public string format;
        
        public checkTextsRequest()
        {
        }
        
        public checkTextsRequest(string[] text, string lang, int options, string format)
        {
            this.text = text;
            this.lang = lang;
            this.options = options;
            this.format = format;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CheckTextsResponse", WrapperNamespace="http://speller.yandex.net/services/spellservice", IsWrapped=true)]
    public partial class checkTextsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://speller.yandex.net/services/spellservice", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("SpellResult", IsNullable=false)]
        [System.Xml.Serialization.XmlArrayItemAttribute("error", IsNullable=false, NestingLevel=1)]
        public YandexSpeller.SpellError[][] ArrayOfSpellResult;
        
        public checkTextsResponse()
        {
        }
        
        public checkTextsResponse(YandexSpeller.SpellError[][] ArrayOfSpellResult)
        {
            this.ArrayOfSpellResult = ArrayOfSpellResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface SpellServiceSoapChannel : YandexSpeller.SpellServiceSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class SpellServiceSoapClient : System.ServiceModel.ClientBase<YandexSpeller.SpellServiceSoap>, YandexSpeller.SpellServiceSoap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public SpellServiceSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(SpellServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), SpellServiceSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SpellServiceSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(SpellServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SpellServiceSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(SpellServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SpellServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<YandexSpeller.checkTextResponse> YandexSpeller.SpellServiceSoap.checkTextAsync(YandexSpeller.checkTextRequest request)
        {
            return base.Channel.checkTextAsync(request);
        }
        
        public System.Threading.Tasks.Task<YandexSpeller.checkTextResponse> checkTextAsync(string text, string lang, int options, string format)
        {
            YandexSpeller.checkTextRequest inValue = new YandexSpeller.checkTextRequest();
            inValue.text = text;
            inValue.lang = lang;
            inValue.options = options;
            inValue.format = format;
            return ((YandexSpeller.SpellServiceSoap)(this)).checkTextAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<YandexSpeller.checkTextsResponse> YandexSpeller.SpellServiceSoap.checkTextsAsync(YandexSpeller.checkTextsRequest request)
        {
            return base.Channel.checkTextsAsync(request);
        }
        
        public System.Threading.Tasks.Task<YandexSpeller.checkTextsResponse> checkTextsAsync(string[] text, string lang, int options, string format)
        {
            YandexSpeller.checkTextsRequest inValue = new YandexSpeller.checkTextsRequest();
            inValue.text = text;
            inValue.lang = lang;
            inValue.options = options;
            inValue.format = format;
            return ((YandexSpeller.SpellServiceSoap)(this)).checkTextsAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.SpellServiceSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.SpellServiceSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.SpellServiceSoap))
            {
                return new System.ServiceModel.EndpointAddress("http://speller.yandex.net/services/spellservice");
            }
            if ((endpointConfiguration == EndpointConfiguration.SpellServiceSoap12))
            {
                return new System.ServiceModel.EndpointAddress("http://speller.yandex.net/services/spellservice");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            SpellServiceSoap,
            
            SpellServiceSoap12,
        }
    }
}
